language: node_js  

node_js:
 - "7.10.1"

addons:
 chrome: stable

before_script:
  - cd src/server
  - npm install

after_failure:
  - cat /TabSolution/travisBugs.log

branches:
  only:
  - travis
  
script:
 - npm run build
